//
// Created by Kirill Shypachov on 19.04.2026.
//

#ifndef CEDAR_SWITCH_3IN4OUT_POWER_NETWORKCOMMISSIONINGCLUSTER_H
#define CEDAR_SWITCH_3IN4OUT_POWER_NETWORKCOMMISSIONINGCLUSTER_H

#include <lib/core/CHIPError.h>

CHIP_ERROR matter_network_commissioning_init();

#endif //CEDAR_SWITCH_3IN4OUT_POWER_NETWORKCOMMISSIONINGCLUSTER_H
