CONFIG_SETTINGS_FILE=n
CONFIG_ZMS=y
CONFIG_SETTINGS_ZMS=y
CONFIG_SETTINGS_ZMS_CUSTOM_SECTOR_COUNT=y
CONFIG_SETTINGS_ZMS_SECTOR_COUNT=32
CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=256
CONFIG_SETTINGS_ZMS_LL_CACHE=y
CONFIG_SETTINGS_ZMS_LOAD_SUBTREE_PATH=y
