//
// Created by Kirill Shypachov on 28.04.2026.
//

#ifndef CEDAR_SWITCH_3IN4OUT_POWER_COMMON_INIT_H
#define CEDAR_SWITCH_3IN4OUT_POWER_COMMON_INIT_H

#endif //CEDAR_SWITCH_3IN4OUT_POWER_COMMON_INIT_H
