//
// Created by Kirill Shypachov on 18.04.2026.
//

#ifndef CEDAR_SWITCH_3IN4OUT_POWER_MATTER_EVENT_LOOP_H
#define CEDAR_SWITCH_3IN4OUT_POWER_MATTER_EVENT_LOOP_H

#endif //CEDAR_SWITCH_3IN4OUT_POWER_MATTER_EVENT_LOOP_H
