//
// Created by Kirill Shypachov on 04.05.2026.
//

#ifndef CEDAR_SWITCH_3IN4OUT_POWER_DEVICE_CONFIG_H
#define CEDAR_SWITCH_3IN4OUT_POWER_DEVICE_CONFIG_H

#endif //CEDAR_SWITCH_3IN4OUT_POWER_DEVICE_CONFIG_H
