# Record the application revision in a header, at build time.
#
# Run as a script (cmake -P) by a target that runs on every build, so the
# revision is the one the sources had when they were compiled, not when the
# build directory was configured. The header is rewritten only when the text
# changes, so an unchanged revision recompiles nothing.
#
#   -DAPP_DIR=<application directory> -DOUT=<header to write>

execute_process(
    COMMAND git describe --always --dirty --abbrev=12
    WORKING_DIRECTORY ${APP_DIR}
    OUTPUT_VARIABLE revision
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE rc
)
if(NOT rc EQUAL 0 OR revision STREQUAL "")
    set(revision "unknown")
endif()

set(text "/* Generated by cmake/cedar_version.cmake. Do not edit. */\n#define CEDAR_FIRMWARE_VERSION \"${revision}\"\n")
if(EXISTS ${OUT})
    file(READ ${OUT} current)
else()
    set(current "")
endif()
if(NOT current STREQUAL text)
    file(WRITE ${OUT} "${text}")
endif()
